### ISSUE TITLE
Missing header.php file produces warning

### ISSUE THREAD

**Issue by johnalarcon** [khacoder/canuck-cp#2]
> Notice: Theme without header.php is deprecated since version WP-3.0.0 with no alternative available. Please include a header.php template in your theme. in /home/user/site/wp-includes/functions.php on line 4039

PHP 7.2
CP 1.2.0
Canuck-CP 1.0.5

I added a blank `header.php` file to fill the requirement, but, it wasn't a viable fix. Let me know if you need any additional details regarding my site or server implementation.

**Comment by khacoder** [comment]
Hopefully fixed in 1.0.6
